<?
$aMenuLinks = Array(
	Array(
		"Главная", 
		"/", 
		Array(), 
		Array("icon"=>"icon-mobile-home"), 
		"" 
	),
	Array(
		"Каталог", 
		"/catalog/", 
		Array(), 
		Array("icon"=>"icon-mobile-catalog", "nolink"=>"yes"), 
		"" 
	),
    Array(
        "Заказы",
        "/personal/orders/",
        Array(),
        Array("icon"=>"icon-orders"),
        ""
    ),
	Array(
		"Избранное", 
		"/favorites/", 
		Array(), 
		Array("icon"=>"icon-heart"), 
		"" 
	),
	Array(
		"Кабинет", 
		"/personal/", 
		Array(), 
		Array("icon"=>"icon-profile-login"), 
		"" 
	)
);
?>